min_version = "2025.11.7"

[tools]
bat = "0.26.1"
btop = "1.4.6"
chezmoi = "latest"
doggo = "1.1.4"
fd = "10.3.0"
fzf = "0.67.0"
github-cli = "2.86.0"
jj = "0.38.0"
lsd = "1.2.0"
neovim = "0.11.6"
node = "25.5.0"
ripgrep = "15.1.0"
starship = "1.24.2"
"ubi:nushell/nushell" = { version = "0.110.0", exe = "nu" }
zellij = "0.43.1"
zoxide = "0.9.8"
opencode = "1.1.53"
"github:peteonrails/voxtype" = { version = "0.4.16", asset_pattern = "voxtype-*-linux-x86_64-vulkan" }
difftastic = "0.67.0"

[settings]
experimental = true
lockfile = true
pin = true

[env]
OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = '240000'

[tasks.llama-server.env]
HF_HUB_ENABLE_HF_TRANSFER = "1"
LLAMA_ARG_HOST = "0.0.0.0"
LLAMA_ARG_PORT = "8080"

[tasks.llama-server]
run = "llama-server --models-preset {{env.MISE_TASK_DIR}}/llama-server.ini"
